import { Buffer } from "node:buffer";
import { E2BSandbox } from "@open-agents/sandbox/e2b";
import type { ControlPlaneStore } from "./db.ts";

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function basicGitHubHeader(token: string): string {
  return `AUTHORIZATION: basic ${Buffer.from(`x-access-token:${token}`).toString("base64")}`;
}

export async function getSessionDiff(
  store: ControlPlaneStore,
  sessionId: string,
): Promise<string> {
  const active = await store.getActiveSandbox(sessionId);
  if (!active) {
    throw new Error("No active sandbox for session");
  }
  const sandbox = await E2BSandbox.connect({
    sandboxId: active.sandboxId,
    repoPath: active.repoPath,
  });
  const result = await sandbox.exec(
    "git diff --binary HEAD",
    active.repoPath,
    120_000,
  );
  if (!result.success) {
    throw new Error(result.stderr || "Failed to read diff");
  }
  return result.stdout;
}

export async function pushAndCreatePr(params: {
  store: ControlPlaneStore;
  sessionId: string;
  githubToken: string;
  title?: string;
  body?: string;
}): Promise<{ url: string; number: number }> {
  const [session, active] = await Promise.all([
    params.store.getSession(params.sessionId),
    params.store.getActiveSandbox(params.sessionId),
  ]);
  if (!session) {
    throw new Error("Session not found");
  }
  if (!active) {
    throw new Error("No active sandbox for session");
  }
  if (!session.repoOwner || !session.repoName) {
    throw new Error("Only GitHub repositories are supported for PR creation");
  }

  const sandbox = await E2BSandbox.connect({
    sandboxId: active.sandboxId,
    repoPath: active.repoPath,
  });
  const branch = `agent/${session.id.slice(0, 8)}`;
  const authHeader = basicGitHubHeader(params.githubToken);
  const push = await sandbox.exec(
    [
      "git",
      "-c",
      `http.https://github.com/.extraheader=${shellQuote(authHeader)}`,
      "push",
      "origin",
      `HEAD:${shellQuote(branch)}`,
    ].join(" "),
    active.repoPath,
    300_000,
  );
  if (!push.success) {
    throw new Error(push.stderr || "Failed to push branch");
  }

  const response = await fetch(
    `https://api.github.com/repos/${session.repoOwner}/${session.repoName}/pulls`,
    {
      method: "POST",
      headers: {
        accept: "application/vnd.github+json",
        authorization: `Bearer ${params.githubToken}`,
        "content-type": "application/json",
        "x-github-api-version": "2022-11-28",
      },
      body: JSON.stringify({
        title: params.title ?? `Agent changes for ${session.repoName}`,
        body: params.body ?? "Generated by the E2B + Codex control plane.",
        head: branch,
        base: session.branch ?? "main",
      }),
    },
  );

  if (!response.ok) {
    throw new Error(`GitHub PR creation failed: ${await response.text()}`);
  }

  const pr = (await response.json()) as { html_url: string; number: number };
  return { url: pr.html_url, number: pr.number };
}
